---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-18.10
  - name: centos-7

suites:
    - name: supermarket
      verifier:
        inspec_tests:
          - test/integration/default

verifier:
    name: inspec
